### PR TITLE
Use Channel token instead of API & Secret keys

### PR DESCRIPTION
**Pull request by bachwehbi**
Channel token limits access to the channel where API & Secret keys provide full API access the Beebotte account.
In addition, it is possible to regenerate the channel token (thus invalidating the existing one) if ever the device or code is compromised!

### CODE REVIEW

**Comment by raspberrycoulis** [comment]
Thanks. I based this on Beebotte's example, but if this makes this script more secure then I'm all for it. Have you tested this works?

**Comment by bachwehbi** [comment]
The API with channel token works, haven't tested the whole script though!

**Comment by raspberrycoulis** [comment]
Ok, thanks. Will check it out and merge.

**Review by raspberrycoulis — APPROVED** [review]
Updated code to use Channel API Key instead of API_KEY and SECRET_KEY for security purposes. Thanks to bachwehbi for pointing this out.

**Pull request merged**
